---
title: "Untitled"
output: github_document
date: "2024-11-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

### Problem 1

```{r}
#birthday function for duplications.
birthday <- function(n) {
  birth <- sample(1:365, n, replace = TRUE)
  any(duplicated(birth))
}
```

```{r}
sizes <- 2:50
simulations <- 10000
prob <- numeric(length(sizes))

#for loop and run the function 10000 times for each group size between 2 and 50. 
for (i in seq_along(sizes)) {
  results <- replicate(simulations, birthday(sizes[i]))
  prob[i] <- mean(results)
}
```

```{r}
#plot
plot(sizes, prob, type = "b", 
     xlab = "Group Size", ylab = "Probability of Shared Birthday",
     main = "Probability",
     pch = 16, col = "blue")

```
Probability increase as group size increase.

### Problem 2
```{r}
#simulate data and perform t-test
simulate <- function(mu, n = 30, sigma = 5, simulations = 5000) {
  p_values <- numeric(simulations)
  estimates <- numeric(simulations)
  
  for (i in 1:simulations) {
    data <- rnorm(n, mean = mu, sd = sigma)
    test <- t.test(data, mu = 0)
    p_values[i] <- test$p.value
    estimates[i] <- mean(data)
  }
  
  list(p_values = p_values, estimates = estimates)
}

```

```{r}
#run the simulations for different mu
mu <- 1:6
results <- map(mu_values, ~ simulate(.x)) %>%
  set_names(mu_values)

# Combine results into one data frame
all_results <- bind_rows(results, .id = "mu") %>%
  mutate(mu = as.numeric(mu))
```

```{r}
#plot showing the proportion of times the null was rejected (the power of the test) on the y axis  
#and the true value of μ on the x axis
power_data <- all_results %>%
  group_by(mu) %>%
  summarize(power = mean(p_values < 0.05))

ggplot(power_data, aes(x = mu, y = power)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Power of the Test vs True Value of Mu",
    x = "True Value of Mu",
    y = "Power"
  ) +
  theme_minimal()
```


